# Generated by Django 4.1 on 2023-05-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simvis", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question",
            new_name="dataInput",
        ),
    ]
